import Head from "next/head";
import styles from "../styles/Home.module.css";
import SehirSecimi from "./sehirsecimi";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Yemek ve Restoran Ara - Yemek Sepeti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.hizliresim.com/tu6gk5j.jfif" />
      </Head>
      <SehirSecimi />
    </div>
  );
}
