import React from "react";
import Head from "next/head";
import Header from "./components/Header";
import Content from "./components/Content";
import Footer from "./components/Footer";
import PageEnd from "./components/PageEnd";
import MobileMenu from "./components/MobileMenu";

export default function sehirsecimi() {
  return (
    <div className="container">
      <Head>
        <title>Yemek ve Restoran Ara - Yemek Sepeti</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSua2SWUfQFk9hGdzb3frXZScE358ZIzqZH0A&usqp=CAU"
        />
      </Head>
      <Header />
      <Content />
      <Footer />
      <PageEnd />
      <MobileMenu />
    </div>
  );
}
