import React from "react";
import Head from "next/head";
import CityHome from "./components/CityHome";
import PageEnd from "./components/PageEnd";
import MobileSehirSecimi from "./components/MobileSehirSecimi";
export default function sehir() {
  return (
    <div>
      {" "}
      <Head>
        <title>Yemek ve Restoran Ara - Yemek Sepeti</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSua2SWUfQFk9hGdzb3frXZScE358ZIzqZH0A&usqp=CAU"
        />
      </Head>
      <CityHome />
      <PageEnd />
      <MobileSehirSecimi />
    </div>
  );
}
